services:
  database:
    image: mysql
    env_file:
      - .env
    ports:
      - 3306:3306

  server:
    build: .
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - 3000:3000

version: '3.9'
