services:
  database:
    build: ./database
    env_file:
      - web/.env
    ports:
      - 27017:27017

  web:
    build: ./web
    depends_on:
      - database
    ports:
      - 3000:3000

version: '3.9'
