services:
  database:
    image: mysql
    env_file:
      - web/.env
    ports:
      - 3306:3306

  web:
    build: ./web
    depends_on:
      - database
    ports:
      - 3000:3000

version: '3.9'
